# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170605_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
