# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0004_auto_20170613_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
    ]
