# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170614_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('supplier', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ManyToManyField(to='website.CompanyModel')),
            ],
        ),
    ]
