# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_incentivemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivemodel',
            name='description',
            field=models.TextField(default='Default Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentivemodel',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
