# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170617_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivemodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
