# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_incentivemodel_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivemodel',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
