# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_taskmodel_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivemodel',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
