# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0017_auto_20170619_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIncentiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('date_completed', models.DateField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('payed', models.BooleanField(default=False)),
                ('incentivemodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.IncentiveModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
