# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_userincentivemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userincentivemodel',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
