# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_companymodel'),
        ('reg_extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CompanyModel'),
            preserve_default=False,
        ),
    ]
