# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_extras', '0003_auto_20170614_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
